- job:
    name: 'ceph-dev-cron'
    node: master
    project-type: freestyle
    defaults: global
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - build-discarder:
          days-to-keep: 1
          num-to-keep: 10
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph
    discard-old-builds: true

    triggers:
      - pollscm:
          cron: |
            TZ=Etc/UTC
            H 14 * * *
            H 20 * * *

    scm:
      - git:
          url: https://github.com/ceph/ceph
          browser: auto
          branches:
            - origin/master
            - origin/pacific
            - origin/octopus
            - origin/nautilus
          skip-tag: true
          timeout: 20
          wipe-workspace: true

    builders:
      # Build luminous on:
      # default: centos7 bionic xenial trusty
      - conditional-step:
          condition-kind: regex-match
          regex: .*luminous.*
          label: '${GIT_BRANCH}'
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw:
                - ../../../scripts/build_utils.sh
                - ../../build/notify
            - trigger-builds:
                - project: 'ceph-dev'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=centos7 bionic xenial trusty
      # build nautilus on:
      # default: bionic xenial centos7 centos8
      - conditional-step:
          condition-kind: regex-match
          regex: .*nautilus.*
          label: '${GIT_BRANCH}'
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw:
                - ../../../scripts/build_utils.sh
                - ../../build/notify
            - trigger-builds:
                - project: 'ceph-dev'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=bionic xenial centos7 centos8
      # build octopus on:
      # default: focal bionic centos7 centos8 leap15
      - conditional-step:
          condition-kind: regex-match
          regex: .*octopus.*
          label: '${GIT_BRANCH}'
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw:
                - ../../../scripts/build_utils.sh
                - ../../build/notify
            - trigger-builds:
                - project: 'ceph-dev'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=focal bionic centos7 centos8 leap15
      # build pacific on:
      # default: focal bionic centos8 centos9 leap15
      # crimson: centos8
      - conditional-step:
          condition-kind: regex-match
          regex: .*pacific.*
          label: '${GIT_BRANCH}'
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw:
                - ../../../scripts/build_utils.sh
                - ../../build/notify
            - trigger-builds:
                - project: 'ceph-dev'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=focal bionic centos8 centos9 leap15
                - project: 'ceph-dev'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=centos8
                    FLAVOR=crimson
                    ARCHS=x86_64
      # build master on:
      # default: focal centos8 centos9 windows
      # crimson: centos8
      - conditional-step:
          condition-kind: regex-match
          regex: .*master.*
          label: '${GIT_BRANCH}'
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw:
                - ../../../scripts/build_utils.sh
                - ../../build/notify
            - trigger-builds:
                - project: 'ceph-dev'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=focal centos8 centos9 windows
                - project: 'ceph-dev'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=centos8
                    FLAVOR=crimson
                    ARCHS=x86_64

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - text:
              credential-id: shaman-api-key
              variable: SHAMAN_API_KEY
