- job:
    name: ceph-dev-new-trigger
    node: master
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - build-discarder:
          days-to-keep: 1
          num-to-keep: 10
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph-ci
    discard-old-builds: true

    triggers:
      - github

    scm:
      - git:
          url: https://github.com/ceph/ceph-ci
          browser: auto
          skip-tag: true
          timeout: 20
          wipe-workspace: true

    builders:
      # Build luminous on:
      # default: centos7 bionic xenial trusty
      - conditional-step:
          condition-kind: regex-match
          regex: .*luminous.*
          label: '${GIT_BRANCH}'
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw:
                - ../../../scripts/build_utils.sh
                - ../../build/notify
            - trigger-builds:
                - project: 'ceph-dev-new'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=centos7 bionic xenial trusty
      # build mimic on:
      # default: bionic xenial centos7
      - conditional-step:
          condition-kind: regex-match
          regex: .*mimic.*
          label: '${GIT_BRANCH}'
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw:
                - ../../../scripts/build_utils.sh
                - ../../build/notify
            - trigger-builds:
                - project: 'ceph-dev-new'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=bionic xenial centos7
      # build nautilus on:
      # default: bionic xenial centos7 centos8
      - conditional-step:
          condition-kind: regex-match
          regex: .*nautilus.*
          label: '${GIT_BRANCH}'
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw:
                - ../../../scripts/build_utils.sh
                - ../../build/notify
            - trigger-builds:
                - project: 'ceph-dev-new'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=bionic xenial centos7 centos8
      # build octopus on:
      # default: focal bionic centos7 centos8 leap15
      - conditional-step:
          condition-kind: regex-match
          regex: .*octopus.*
          label: '${GIT_BRANCH}'
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw:
                - ../../../scripts/build_utils.sh
                - ../../build/notify
            - trigger-builds:
                - project: 'ceph-dev-new'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=focal bionic centos7 centos8 leap15
      # build pacific on:
      # default: focal bionic centos8 centos9
      # crimson: centos8
      - conditional-step:
          condition-kind: regex-match
          regex: .*pacific.*
          label: '${GIT_BRANCH}'
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw:
                - ../../../scripts/build_utils.sh
                - ../../build/notify
            - trigger-builds:
                - project: 'ceph-dev-new'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=focal bionic centos8 centos9 windows
                - project: 'ceph-dev-new'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=centos8
                    FLAVOR=crimson
                    ARCHS=x86_64
      # If no release name is found in branch, build on all possible distro/flavor combos (except xenial and bionic).
      # regex matching and 'on-evaluation-failure: run' doesn't work here so triple negative it is.
      - conditional-step:
          condition-kind: shell
          condition-command: |
            echo "${GIT_BRANCH}" | grep -v '\(luminous\|mimic\|nautilus\|octopus\|pacific\|crimson-only\|jaeger\)'
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw:
                - ../../../scripts/build_utils.sh
                - ../../build/notify
            - trigger-builds:
                - project: 'ceph-dev-new'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=focal centos8 windows
            - trigger-builds:
                - project: 'ceph-dev-new'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=centos8
                    FLAVOR=crimson
                    ARCHS=x86_64
      # Build only the `crimson` flavour, don't waste resources on the default one.
      # Useful for the crimson's bug-hunt at Sepia
      # crimson: centos8
      - conditional-step:
          condition-kind: regex-match
          regex: .*crimson-only.*
          label: '${GIT_BRANCH}'
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw:
                - ../../../scripts/build_utils.sh
                - ../../build/notify
            - trigger-builds:
                - project: 'ceph-dev-new'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=centos8
                    FLAVOR=crimson
                    ARCHS=x86_64
      # Build jaegertracing branch on needed env,  don't waste resources on the default one.
      # Useful for testing specific builds failure
      # default: focal, centos8
      - conditional-step:
          condition-kind: regex-match
          regex: .*jaeger.*
          label: '${GIT_BRANCH}'
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw:
                - ../../../scripts/build_utils.sh
                - ../../build/notify
            - trigger-builds:
                - project: 'ceph-dev-new'
                  predefined-parameters: |
                    BRANCH=${GIT_BRANCH}
                    FORCE=True
                    DISTROS=centos8 focal
                    FLAVOR=jaeger
                    ARCHS=x86_64

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - text:
              credential-id: shaman-api-key
              variable: SHAMAN_API_KEY
